// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjnJN_IPbtaQ-hwma-d1ZljtcZuId7ggg',
    appId: '1:450921051126:web:45b2df56b26426de254dd7',
    messagingSenderId: '450921051126',
    projectId: 'decidot',
    authDomain: 'decidot.firebaseapp.com',
    databaseURL: 'https://decidot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'decidot.appspot.com',
    measurementId: 'G-M97L7CEPH1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARKDjYmge_lM-1STW6IFZjkB6ArPUGzk0',
    appId: '1:450921051126:android:c5e0fe91ebc5c14b254dd7',
    messagingSenderId: '450921051126',
    projectId: 'decidot',
    databaseURL: 'https://decidot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'decidot.appspot.com',
  );
}
